### ISSUE TITLE
services with SSL

### ISSUE THREAD

**Issue by samouds** [rawmind0/alpine-traefik#8]
Hello,

I just tried traefik on rancher with a node app and it's working for http. But how can I setup https for this app with letsencrypt ?

Thanks

**Comment by rawmind0** [comment]
Hi @samouds ,

as you could read at README.md, you could add letsencript support (ACME), setting this env variables to traefik service,
TRAEFIK_ACME_ENABLE="false" # Enable/disable traefik ACME feature
TRAEFIK_ACME_EMAIL="test@traefik.io" # Default email
TRAEFIK_ACME_ONDEMAND="true" # ACME ondemand parameter

In your service, you have to add traefik.acme = "true" to automatically configures traefik to use ACME in this site.

Best regards....

**Comment by tlvenn** [comment]
@rawmind0 I think people are not generally aware of the ACME acronym but `letsencrypt` which is a provider is something they are familiar with. I think you should update the README to add a note that ACME is provided by `letsencrypt`

**Comment by rawmind0** [comment]
@tlvenn...README updated...

**Comment by samouds** [comment]
Thanks it's working now.

But when I set TRAEFIK_HTTPS_ENABLE to only, the http redirection of services to https does not work ... I can't reach them

**Comment by rawmind0** [comment]
Hi @samouds , thanks for the feedback. 

Your are right it didn't work in this case. It's solved in the last release. :)

Best regards.....

**Comment by samouds** [comment]
@rawmind0 I updated alpine-traefik to 1.0.2-6 but still have the same problem : 
http://service.example.com -> https://service.example.com:8443 KO (instead of https://service.example.com)

**Comment by rawmind0** [comment]
@samouds , the version of alpine-traefik is not the only change. docker-compose is modified too. 
You don't deploy the service correctly. Deploy it from the package, or updtae it in the correct way. Look at the docler-compose modifications.

Best regards..
